### ISSUE TITLE
supression automatique de marqueurs non demandé lors de l'utilisation du plugin wasabeeMarkers.user.js

### ISSUE THREAD

**Issue by cobra7476** [xscreach/iitc-plugins#1]
bonjour

l'or ce que j'effectue un placement de marqueurs automatique, les marqueurs sont bien placé, mais les marqueurs présent sur l'ecran se retrouvent supprimé automatiquement. cela est peut etre un choix, mais est-il possible d'avoir une case pour modifier ce comportement?

voici la règle appliquée: je marque automatiquement tout les portails machina
![régle_appliqué](https://github.com/xscreach/iitc-plugins/assets/95911575/5aa386f3-90eb-4abb-9cde-9d0e42673900)

la situation de base
![situation initiale](https://github.com/xscreach/iitc-plugins/assets/95911575/fd2fd355-fbeb-4b09-a9f6-5f6ac2bde1b9)

une fois la règle appliquée, j'obtiens cela:
![situation finale](https://github.com/xscreach/iitc-plugins/assets/95911575/2135ab24-6207-4321-b3cb-370a47710f15)

les marqueurs "terminé" ont été supprimé, hors ma volonté est de les garder... est-il possible d'ajouter dans les options une case à cocher, qui pourrait s'intituler "supprimer les marqueurs visibles avant marquage automatique"

d'apprés mes tests, les marqueurs sont supprimé indépendamment de leurs état, ou méme de leurs type

**Comment by xscreach** [comment]
Added option to "keep completed markers" and fixed marker removal - only configured marker types will be removed
